### ISSUE TITLE
Duplicate events received after reconnecting

### ISSUE THREAD

**Issue by opilo** [pusher/pusher-websocket-unity#28]
Hello
I receive duplicate events after the client reconnects to the pusher server. The pusher's Debug console shows that the client, while is not disconnected yet on the server side, subscribes to the same channel (A private channel in this case) again.

Thank you

**Comment by twomedia** [comment]
For us, we had to add a special check to ensure that we only added the event bind if we hadn't done so already, otherwise when we reconnect and subscribe to channels it'll add duplicate binds. We did this by checking if `_pusher.Channels` contained the channel we were trying to subscribe to, if it did then we don't bind.
